server:
  servlet:
    context-path: /spring6x
  port: 8080

logging:
  level:
    root: info


spring:
#  profiles:
#    active: sit
  main:
    allow-circular-references: true #循序循环依赖
  application:
    name: spring6x
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: A123@bpg
    url: jdbc:mysql://10.10.22.173:3306/om_dpi?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    druid:
      # 初始化大小，最小，最大，超时链接，空闲时间，生产时间，pscache
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  data: # MongoDB 配置
    mongodb:
      uri: mongodb://dsri:123456@10.10.22.171:27017/fault_data_samples
#      host: 10.10.22.171
#      port: 27017
#      database: fault_data_samples
#      username: dsri
#      password: 123456

# mybatis-plus 配置
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true


